name = "Lax871432Proofs"
defaultTargets = ["Lax871432Proofs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax68"
git = "https://github.com/lax-archive/lax-submissions"
rev = "f179bc81671b353be657432784d7dee68486b0bd"
subDir = "planar-graph-classes-v4-33/concepts"

[[require]]
name = "Lax199508"
git = "https://github.com/lax-archive/lax-submissions"
rev = "e9845c204d14a5678f9d64c0e6f4ca757d9dc9d0"
subDir = "sparsity-lectures-v4-33/concepts"

[[require]]
name = "Lax871432"
path = "../concepts"

[[lean_lib]]
name = "Lax871432Proofs"
